# Generated by Django 5.0.1 on 2024-02-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='partnerjam_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
